import { Header } from "@/components/app_layout/Header";
import { LeftBar } from "@/components/app_layout/LeftBar";
import { cn } from "@/utils/cn";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en" className="h-screen w-full">
      <Header />
      <div className={cn(inter.className, "w-full flex flex-row pt-12")}>
        <LeftBar />
        <div className="h-full w-full ml-64">{children}</div>
      </div>
    </div>
  );
}
